'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace TomaFisica.Entities

    Partial Public Class FISICO_DETALLE
        Public Property Numero As Decimal
        Public Property Producto As String
        Public Property Tipo As Integer
        Public Property Empresa As Integer
        Public Property Descripcion As String
        Public Property Cantidad As Decimal
        Public Property Costo As Nullable(Of Decimal)
        Public Property Precio As Nullable(Of Decimal)
        Public Property Medida As Nullable(Of Integer)
        Public Property Descripcion_Medida As String
        Public Property Cantidad_Medida As Nullable(Of Decimal)
        Public Property Lote As String
        Public Property Fecha_Vencimiento As Nullable(Of Date)
        Public Property posicion_fisica As Integer
        Public Property bodega As Integer
        Public Property Fecha As Nullable(Of Date)
    
    End Class

End Namespace
