'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace TomaFisica.Entities

    Partial Public Class ITSEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=ITSEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property FISICO_DETALLE() As DbSet(Of FISICO_DETALLE)
        Public Overridable Property FISICO_MAESTRO() As DbSet(Of FISICO_MAESTRO)
    
    End Class

End Namespace
