'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace TomaFisicaEntidades

    Partial Public Class FISICO_MAESTRO
        Public Property Numero As Decimal
        Public Property Tipo As Integer
        Public Property Empresa As Integer
        Public Property Fecha As Date
        Public Property Observaciones As String
        Public Property Estatus As String
        Public Property Usuario As String
        Public Property Fecha_Anulacion As Nullable(Of Date)
        Public Property Sucursal As Nullable(Of Integer)
        Public Property Bodega As Integer
    
    End Class

End Namespace
